print("The Cardinals will make the playoffs this year.")
print("I'm excited to be back on campus")
print("I feel smart.")
print("I don't know what else to say.")
print("\t I'm excited to learn programming.")